services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - STORAGE_STRATEGY=file-system
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/repsy
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET_NAME=repsy-bucket
    depends_on:
      - db
      - minio

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=repsy
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio
    command: server /data
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio-data:/data